### ISSUE TITLE
Warning: You are using a version of node-ipc containing malicious code

### ISSUE THREAD

**Issue by onixldlc** [AjRadwan/Covid-Tracker#1]
I just wanted to warn you about a current version of node-ipc containing https://github.com/RIAEvangelist/peacenotwar. You should probably pin your dependencies. It was classified as 9.8/10 severity by snyk.

You can read more about it here:
https://github.com/RIAEvangelist/node-ipc/issues/233
https://security.snyk.io/vuln/SNYK-JS-NODEIPC-2426370

for temporary mitigation:
https://gist.github.com/MidSpike/f7ae3457420af78a54b38a31cc0c809c#available-mitigation-methods

**Comment by AjRadwan** [comment]
Hey @onixldlc, Thank you for letting me know. It was just a project I was doing for practicing vue.js so the risk is tolerable to this project. but if you want you can fix this.
